load('latlongelevmapping.mat')
latlongelevmapping = sortrows(latlongelevmapping,[1 2], 'ascend');
latlong_interp = scatteredInterpolant(latlongelevmapping.lat,...
    latlongelevmapping.long,...
    latlongelevmapping.elev,...
    'linear',...
    'nearest');